name: "Configuration"
description: "Configurer Python et installer les dépendances"
runs:
  using: "composite"
  steps:
    - name: Checkout du code
      uses: actions/checkout@v3
    - name: Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
inputs:
  python-version:
    description: "Version de Python"
    required: true
