name: CI - Installation et Tests

on:
  push:
    branches:
      - dev
      - main
      - 5-create-gitlab-ci
  pull_request:
    branches:
      - dev
      - main
      - 5-create-gitlab-ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifiez le code source
    - name: Checkout du code
      uses: actions/checkout@v3

    # Étape 2 : Configurez Python
    - name: Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Changez selon la version requise

    # Étape 3 : Exporter les variables d'environnement
    - name: Configuration des variables d'environnement
      env:
        API_USER: ${{ secrets.API_USER }} # Exemple de variable
        API_KEY: ${{ secrets.API_KEY }} # Exemple de variable
        API_PRIVATE: ${{ secrets.API_PRIVATE }} # Exemple de variable

      run: |
        echo "Variables d'environnement configurées."
        echo "USER = $API_USER"
    # Étape 4 : Installez les dépendances
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 5 : Exécutez les tests
    - name: Exécution des tests
      env:
        API_USER: ${{ secrets.API_USER }}
        API_KEY: ${{ secrets.API_KEY }}
        API_PRIVATE: ${{ secrets.API_PRIVATE }}
      run: |
        pytest --cov=mon_module --cov-fail-under=75 --cov-report=xml
    # Etape 6: appliquer codecov
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: echesneau/pytradingbot
