name: CI - Tests et Qualité de Code

on:
  push:
    branches:
      - dev
      - main
      - 5-create-gitlab-ci
  pull_request:
    branches:
      - dev
      - main
      - 5-create-gitlab-ci

env:
  API_USER: ${{ secrets.API_USER }}
  API_KEY: ${{ secrets.API_KEY }}
  API_PRIVATE: ${{ secrets.API_PRIVATE }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Analyse de qualité avec Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Analyse de format avec Black
      run: |
        black --diff . || true > black_warnings.txt
      continue-on-error: true

    - name: Sauvegarder les résultats de Black
      uses: actions/upload-artifact@v3
      with:
        name: black-warnings
        path: black_warnings.txt

    - name: Analyse approfondie avec Pylint
      run: |
        pylint pytradingbot || true

    - name: Analyse de sécurité avec Bandit
      run: |
        bandit -r pytradingbot --exclude pytradingbot/tests/ || true
